### ISSUE TITLE
Link https://nextcloud.com/buy points to empty page

### ISSUE THREAD

**Issue by ovpc** [nextcloud/website#16]
On (almost) every page on nextcloud.com there is a button "Get a Quote"

Suggest change link 

- create a contact form [Edit]  use existing one /enterprise/buy/

**Comment by skjnldsv** [comment]
@jospoortvliet

**Comment by jospoortvliet** [comment]
Somehow redirects in wordpress got broken and are still broken, but I added a manual one so it's back. Thanks for reporting!
