### ISSUE TITLE
German website has overlapping menu entries

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/website#9]
Set germans as website language and you will see:

<img width="1001" alt="bildschirmfoto 2018-09-08 um 10 06 28" src="https://user-images.githubusercontent.com/2069590/45251962-4cf96080-b34f-11e8-9c45-23c882bc6a88.png">

Not sure if we need to shorten german translation or the menu item width can be fixed.

**Comment by skjnldsv** [comment]
@rakekniven please report back to https://github.com/nextcloud/nextcloud.com
